version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      web:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
    groups:
      infrastructure:
        patterns: ["*"]
