"use client";

import Link from "next/link";
import { useState } from "react";
import { BrandMark, Icon, StatusPill } from "@paritylab/ui";

export function LoginPage() {
  return <main className="access-page"><header><Link href="/"><BrandMark /></Link><span>Sandbox-only reliability lab</span></header><section className="access-card"><span className="access-index mono">ACCESS / LOCAL</span><h1>Enter the control plane.</h1><p>Authentication is not connected yet. Continue into the explicitly labeled local product preview without creating an account.</p><div className="access-safety"><Icon name="check"/><span><strong>No production access</strong><small>This path loads seeded data or your local sandbox engine only.</small></span></div><Link className="button button--primary" href="/dashboard">Continue to local preview <Icon name="arrow"/></Link><Link className="text-link" href="/">Return to website</Link></section></main>;
}

export function OnboardingPage() {
  const [step, setStep] = useState(1);
  const [copied, setCopied] = useState(false);
  const copyTemplate = async () => { await navigator.clipboard.writeText("PARITYLAB_ENCRYPTION_KEY=generate-32-byte-key\nNEXT_PUBLIC_PARITYLAB_API_URL=http://127.0.0.1:8080"); setCopied(true); };
  return <main className="access-page onboarding-page"><header><Link href="/"><BrandMark /></Link><Link href="/dashboard">Exit setup</Link></header><section className="onboarding-shell"><aside><span className="mono">SETUP / 03</span><h1>Prepare a safe verification workspace.</h1><ol>{["Workspace", "API safety", "Stripe Sandbox"].map((label, index) => <li key={label} className={step === index + 1 ? "is-active" : step > index + 1 ? "is-complete" : ""}><span>{step > index + 1 ? "✓" : index + 1}</span>{label}</li>)}</ol></aside><div className="onboarding-content">{step === 1 ? <><StatusPill tone="neutral">Local preview</StatusPill><h2>Name the verification surface</h2><p>This browser-only setup does not create an account or organization record.</p><label>Workspace name<input defaultValue="Platform team" /></label><button className="button button--primary" onClick={() => setStep(2)}>Continue <Icon name="arrow"/></button></> : step === 2 ? <><StatusPill tone="warning">Backend prerequisite</StatusPill><h2>Enable encrypted connection storage</h2><p>The API needs its encryption key before it can accept a restricted Stripe Sandbox key. Put this non-Stripe configuration in an ignored <code>.env.local</code> file and restart the engine.</p><pre>PARITYLAB_ENCRYPTION_KEY=generate-32-byte-key{"\n"}NEXT_PUBLIC_PARITYLAB_API_URL=http://127.0.0.1:8080</pre><button className="button button--secondary" onClick={copyTemplate}>{copied ? "Template copied" : "Copy environment template"}</button><button className="button button--primary" onClick={() => setStep(3)}>Continue to secure connection <Icon name="arrow"/></button></> : <><StatusPill tone="neutral">Secure API handoff</StatusPill><h2>Validate a restricted Sandbox key</h2><p>The Connections screen posts the key directly to the API, clears the input immediately, and only renders the sanitized connection record returned by the backend.</p><Link className="button button--primary" href="/connections">Open secure Stripe connection <Icon name="arrow"/></Link><button className="button button--quiet" onClick={() => setStep(2)}>Back to configuration</button></>}</div></section></main>;
}
